### PR TITLE
[14912] Remove non-ASCII character from source

### LINKED ISSUE #53: gradle build failed: unmappable character (0xC3) for encoding US-ASCII [13729]
Non ascii symbol at line [com/eprosima/fastdds/idl/grammar/Context.java:283](https://github.com/eProsima/Fast-DDS-Gen/blob/master/src/main/java/com/eprosima/fastdds/idl/grammar/Context.java#L283) causes gradel build failure

```gradle
# gradle build

> Task :submodulesUpdate
Submodule path 'thirdparty/idl-parser': checked out '69a469c48ca0456a32b4eeea28aed8d58fa82845'

> Task :compileJava
/root/workspace/Fast-DDS-Gen/src/main/java/com/eprosima/fastdds/idl/grammar/Context.java:283: error: unmappable character (0xC3) for encoding US-ASCII
    // TODO Lleva la cuenta de generaci??n de nuevos nombres.
                                       ^
/root/workspace/Fast-DDS-Gen/src/main/java/com/eprosima/fastdds/idl/grammar/Context.java:283: error: unmappable character (0xB3) for encoding US-ASCII
    // TODO Lleva la cuenta de generaci??n de nuevos nombres.
```

### PR DESCRIPTION
**Pull request by panicgh**
Prefer pure ASCII, avoid UTF8 in sources. Fixes #53.

Signed-off-by: Nicolas Benes <nbenes.gh@xandea.de>

### CODE REVIEW

File: src/main/java/com/eprosima/fastdds/idl/grammar/Context.java [hunk 1]
```diff
@@ -298,7 +298,7 @@ public String getPackageUnder()
     //! Cache the first exception.
     private com.eprosima.idl.parser.tree.Exception m_firstexception = null;
 
-    // TODO Lleva la cuenta de generación de nuevos nombres.
+    // TODO Lleva la cuenta de generacion de nuevos nombres.
```
Comment (EduPonz) [inline src/main/java/com/eprosima/fastdds/idl/grammar/Context.java:301]: I'd rather default to English actually. What about?
```suggestion
    // TODO Keeps new names generation count.
```

**Review by EduPonz — CHANGES_REQUESTED** [review]

File: src/main/java/com/eprosima/fastdds/idl/grammar/Context.java (hunk 1 above)
Comment (panicgh) [reply src/main/java/com/eprosima/fastdds/idl/grammar/Context.java]: You are actually correct. I changed the comment and some others in the file to English. Please re-check if the change preserves the meaning (I'm not entirely sure, since I'd expect an imperative form after a TODO).

**Review by richiware — APPROVED** [review]
